[platformio]
default_envs = espwroom32_test

[env]
platform = espressif32@6.2.0
platform_packages =
    platformio/tool-mklittlefs@~1.203.0
board = esp32dev
framework = arduino
upload_protocol = esptool
monitor_speed = 115200
board_build.filesystem = littlefs
;board_build.flash_mode = dio
board_build.partitions = 4M-default_nvs.csv
lib_ignore = 
    ESP32 BLE Arduino
lib_deps = 
	bblanchon/ArduinoJson@6.21.6
	hieromon/AutoConnect@1.4.2
	end2endzone/NonBlockingRTTTL@1.4.0
	adafruit/Adafruit Unified Sensor@1.1.15
	fastled/FastLED@3.10.3
	adafruit/DHT sensor library@1.4.7
	adafruit/RTClib@2.1.4
	https://github.com/RobTillaart/MultiMap/archive/refs/tags/0.1.7.zip
	kosme/arduinoFFT@1.6.2

[env:espwroom32]
build_flags =
    -Os
    -D FASTLED_ESP32_FLASH_LOCK=0
    -D TEST_CLOCK=false
 ; -mfix-esp32-psram-cache-issue
 ; -D CORS_DEBUG
;  -D USE_OTA
;  -D USE_HTTPUPDATE

[env:espwroom32_test]
build_flags =
    -Os
    -D FASTLED_ESP32_FLASH_LOCK=0
    -D TEST_CLOCK=true
;	-D HAS_ONLINEWEATHER=false
;	-D HAS_USWEATHER=false
 ; -mfix-esp32-psram-cache-issue
 ; -D CORS_DEBUG
;  -D USE_OTA
;  -D USE_HTTPUPDATE

[env:espwroom32_isolation]
build_flags =
    -Os
    -D FASTLED_ESP32_FLASH_LOCK=0
    -D TEST_CLOCK=true
    -D SHELFCLOCK_ISOLATION=true
    -D HAS_ONLINEWEATHER=false
    -D HAS_USWEATHER=false
